### ISSUE TITLE
Forth tag

### ISSUE THREAD

**Issue by FForth** [parrot/forth#2]
Please create a "Forth" tag and ... for this project.

**Comment by FForth** [comment]
Please have a look at the https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics — the topics describe a repository in GitHub.

**Comment by rurban** [comment]
Sorry, internal problems. Looks like even as maintainer I cannot maintain it anymore. No permissions.

**Comment by NotFound** [comment]
I've been able to do it.
